### ISSUE TITLE
notifications show ERROR on test failure, instead of showing FAILED.

### ISSUE THREAD

**Issue by srrvnn** [petrbela/karma-osx-reporter#10]
index.js:80 checks for results.error and sets the appropriate message. but this message is set to ERROR even if tests simply failed, in which case the first else-if needs to run. 

karma0.12.32 sets results.error to true on test failure.

**Comment by petrbela** [comment]
Hi, I'm running 0.12.36, and I'm getting FAILED message when the tests fail. Are you getting ERROR consistently, on only in some case/project?

**Comment by petrbela** [comment]
@srrvnn is the issue still present?
