### ISSUE TITLE
Not detecting that Karma is installed

### ISSUE THREAD

**Issue by adamzerner** [petrbela/karma-osx-reporter#12]
```
code/clutter [master] » npm install -g karma-osx-reporter
/usr/local/lib
├── UNMET PEER DEPENDENCY karma@>=0.9
└── karma-osx-reporter@0.2.1

npm WARN karma-osx-reporter@0.2.1 requires a peer of karma@>=0.9 but none was installed.
code/clutter [master] » karma --version
Karma version: 0.13.22
code/clutter [master] » which karma
./node_modules/.bin/karma
```

It's saying "but none was installed". However, the following two commands make me think that Karma is installed and is `>=0.9`. I've also been using Karma successfully in this project for a while.

**Comment by petrbela** [comment]
You're running `npm install -g karma-osx-reporter`, which installs it globally. Is your `karma` also installed globally? Did you add the `-g` toggle when running `npm install karma`?

Usually, the recommended setup is to have each package declared locally to each project. The only thing you install globally is [karma-cli](https://github.com/karma-runner/karma-cli), which enables you to run `karma` on the command line but in fact it starts the project-specific karma instance.

Can you see if that might be the problem?

**Comment by adamzerner** [comment]
You're right, I was mistaking `karma-cli` for `karma`. `npm install karma -g` worked, thanks.
